Add views
dennis-every/blog-app pull request #6
Opened 2023-05-10 12:18 UTC by dennis-every

In this pull request, we completed the following project requirements:

#### Implement the design from the sneak peek wireframes.
- Styling is nice to have but focus on making sure everything functions first. 
- Note: Ignore login logic, you would be using Devise in coming milestone
- Note: Analyze the wireframes deeply and try to identify all the necessary elements and how a user would navigate from one page to another
- Use methods that you have created in the [Blog App - processing data in models](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project.md).
- Hint: In order to see some posts or comments, you might need to add some data to your database as described [here](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project.md#use-models-to-insert-data).

2023-05-10 17:03 UTC, KDlamini requested changes
### Hi @dennis-every 🙋‍♀️,  

Excellent work! 💯 
You have done a great job creating views for the Rails Blog app 🎊 
There are some issues that you still need to work on to improve your project according to the requirements. You are almost there! 💪🏾 

## Highlights 🌞 

✔️  Good PR title and description
✔️  Users controller `#index` action renders all users
✔️  `#recent_post` method is used to render the user's 3 most recent posts
✔️  `See all Post` link opens the user's post index as displayed on the wireframe
✔️  `post.recent_comments` is used to render 5 most recent comments

## Required Changes ♻️
 
**Kindly look through the comments below 👇 for required changes**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-10 17:03 UTC, KDlamini commented on app/controllers/posts_controller.rb
Well done adding views for Users and Posts index and show pages. The design follows the wireframe! 👏🏾💯 

However, there's a problem with getting all attributes to display on the page. I cannot create user posts and comments. This is because of the following reasons: 

- That is because you do not have the `create` action in the `posts_controller.rb` which is responsible for creating new posts. I should be able to see any posts I create for a user at this point.
- You are also missing the `comments` and `likes` controllers. Which is why creating comments with the test code fails.

You can add the following test code to your `db/seeds.rb` file so that it's easy for us to populate the database. Rember that you are required:
- For Creating at least one user by running the following code.
- For Creating at least 4 posts written by one of the users you created
- For Creating at least 6 posts comments for one of the posts you created

```ruby
first_user = User.create(name: 'Tom', photo: 'https://unsplash.com/photos/F_-0BxGuVvo', bio: 'Teacher from Mexico.')
second_user = User.create(name: 'Lilly', photo: 'https://unsplash.com/photos/F_-0BxGuVvo', bio: 'Teacher from Poland.')

first_post = Post.create(author: first_user, title: 'Hello', text: 'This is my first post')
second_post = Post.create(author: first_user, title: 'Hello', text: 'This is my second post')
third_post = Post.create(author: first_user, title: 'Hello', text: 'This is my third post')
fourth_post = Post.create(author: first_user, title: 'Hello', text: 'This is my fourth post')

Comment.create(post: first_post, author: second_user, text: 'Hi Tom!' )
```

In the test code above, I only added 1 comment. You can add the other 5 comments to make it 6. Then run `rails db:seed` to populate the database.

After run the code I got this from your views.

> // Users index page
![image](https://github.com/dennis-every/blog-app/assets/38088818/616ea036-eee5-4cd9-a70b-7aa1d2d72b58)

> // User show page

![image](https://github.com/dennis-every/blog-app/assets/38088818/d923a42b-3bd5-4eb6-8e99-aa3edef8c653)

- Since I created 4 posts for Tom and 1 comment on one of Tom's posts. I should be seeing 3 recent posts on the user show page for Tom.

2023-05-11 02:07 UTC, dennis-every commented on app/controllers/posts_controller.rb
Hi @KDlamini - tks for your feedback, however, I'm afraid they are not aligned with the requirements.
- [Per the project requirements] (https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project.md) we should create the objects through the rails console - not using a db seed file.
- There are no requirements to add a likes controller or a comments controller, and you do not need these controllers to create these like and comment records - they can be created using the model in the rails console.
- You do not need a create action in the posts controller to create post records - this can be done through the model in the rails console and also there are no buttons or links in the wireframes which would map this controller action.
- The posts you are creating are not being created because you are missing an attribute. Please refer to the Post spec file for some examples of how to create posts appropriately. 
- Appreciate if you can kindly review the code within the context of the project requirements - Tks!

2023-05-11 08:42 UTC, ahmetbozaci commented
### Hello @dennis-every 
### _This is an additional review as a result of the second opinion request._ 

- It seems that you have completed the required tasks for this milestone. I can create users, posts, comments in the rails console and views match the vireframe.
- Creating seed file is optional.
- Creating action in the post controller in the form milestone.
_**Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approved right away**_

- [x] _OPTIONAL_  - Only thing is user photo is not appear in the view. I didn't check clearly what is wrong. If it is same on your side you can fix it. I used this link for photo "https://unsplash.com/photos/F_-0BxGuVvo"


![image](https://github.com/dennis-every/blog-app/assets/38635158/a8fd9922-5f08-4acf-8227-11076d296a31)
![image](https://github.com/dennis-every/blog-app/assets/38635158/67111a85-e693-4cdf-86bb-d0c8f72f9158)
![image](https://github.com/dennis-every/blog-app/assets/38635158/9bd1ea3e-f20a-42de-9e3f-bc4bd9c7d5b6)
![image](https://github.com/dennis-every/blog-app/assets/38635158/470dd7c4-5848-4fe5-8cd8-79d019e913f7)

___




### Cheers and Happy coding! 💻 👏
____
[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2023-05-11 09:06 UTC, KDlamini commented on app/controllers/posts_controller.rb
@dennis-every You are right, the project requirements requested that you use `rails c` to populate data. `rails db:seed` is just another way to do it. The reason I asked that you added the test code in the seeds file was because the test code provided by the project requirements was not working in both `rails c` and `rails db:seed` commands.

I see that @ahmetbozaci has confirmed that your views are working correctly. Congratulations and well done!!! 💯 

Cheers 🥂 and happy coding! 🍻

2023-05-11 12:16 UTC, dennis-every commented on app/controllers/posts_controller.rb
Hi @KDlamini - great! Thanks for the review!

2023-05-11 12:19 UTC, dennis-every commented
Hi @ahmetbozaci - great, thanks for the feedback. On the optional suggestions, seems the link you posted is for a webpage and it not a valid image URL. I have to assume that such a validation is out of scope for now. You can generate a valid image URL with this: Faker::LoremFlickr.image

2023-05-11 12:24 UTC, ichala approved these changes
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-11 13:34 UTC, merged